.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Timothy Gu <timothygu99@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)

.TH ALACCONVERT 1 "June 4, 2013"

.\" Please adjust this date whenever revising the manpage.

.SH NAME
alacconvert \- Apple Lossless Audio Encoder and Decoder
.SH SYNOPSIS
.B alacconvert
.I "input-file" " output-file"
.SH DESCRIPTION
This manual page documents briefly the
.B alacconvert
commands.
.PP
\fBalacconvert\fP is a program that convert WAV in WAV or CAF
container to Apple Lossless in CAF container and vice versa.
.SH ARGUMENTS
alacconvert accepts exactly 2 arguments, no more no less.
.TP
.B input-file
The input file. May be CAF with ALAC for decoding, or CAF/WAV
with PCM for encoding.
.TP
.B output-file
The output file. May be CAF/WAV with PCM for decoding, or CAF
with ALAC for encoding.
.\" .SH SEE ALSO
.\" .BR bar (1),
.\" .BR baz (1).
.\" .br
.\" The programs are documented fully by
.\" .IR "The Rise and Fall of a Fooish Bar" ,
.\" available via the Info system.
